In [2]:
import polars as pl
import os

import pandas as pd
import caveclient

%load_ext autoreload
%autoreload 2

# MICRONS

In [2]:
datalake_root = "/data/microns1412/"

In [3]:
featdef_df = pl.read_delta(os.path.join(datalake_root, 'cellfeaturedefinition'))

In [24]:
featdef_df.head()

shape: (5, 6)
┌──────────────────┬──────────────────────┬────────────────┬───────────┬───────────┬───────────┐
│ id               ┆ description          ┆ unit           ┆ data_type ┆ range_min ┆ range_max │
│ ---              ┆ ---                  ┆ ---            ┆ ---       ┆ ---       ┆ ---       │
│ str              ┆ str                  ┆ str            ┆ str       ┆ f64       ┆ f64       │
╞══════════════════╪══════════════════════╪════════════════╪═══════════╪═══════════╪═══════════╡
│ x_umap           ┆ umap low dimensional ┆ ARBITRARY_UNIT ┆ <f4       ┆ null      ┆ null      │
│                  ┆ embedding…           ┆                ┆           ┆           ┆           │
│ y_umap           ┆ umap low dimensional ┆ ARBITRARY_UNIT ┆ <f4       ┆ null      ┆ null      │
│                  ┆ embedding…           ┆                ┆           ┆           ┆           │
│ x_medial-lateral ┆ The x coordinate in  ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…          ┆                ┆           ┆           ┆           │
│ y_dorsal-ventral ┆ The y coordinate in  ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…          ┆                ┆           ┆           ┆           │
│ z_caudal-rostral ┆ The z coordinate in  ┆ MICRONS_LENGTH ┆ <f4       ┆ null      ┆ null      │
│                  ┆ minnie65 a…          ┆                ┆           ┆           ┆           │
└──────────────────┴──────────────────────┴────────────────┴───────────┴───────────┴───────────┘

In [17]:
print("\n".join(featdef_df["id"].to_list()))

x_umap
y_umap
x_medial-lateral
y_dorsal-ventral
z_caudal-rostral
nucleus_volume_um
nucleus_area_um
nuclear_area_to_volume_ratio
nuclear_folding_area_um
fraction_nuclear_folding
nucleus_to_soma_ratio
soma_volume_um
soma_area_um
soma_to_nucleus_center_dist
soma_area_to_volume_ratio
soma_synapse_density_um
tip_len_dist_dendrite_p75
tip_tort_dendrite_p75
num_syn_dendrite
num_syn_soma
path_length_dendrite
radial_extent_dendrite
syn_dist_distribution_dendrite_p50
syn_size_distribution_soma_p50
syn_size_distribution_dendrite_p50
syn_size_distribution_dendrite_p5
syn_size_distribution_dendrite_p95
syn_size_dendrite_cv
syn_depth_dist_p1
syn_depth_dist_p99
syn_depth_extent
median_density
radius_dist
area_factor
dendrite_length_binned_0
dendrite_length_binned_1
dendrite_length_binned_2
dendrite_length_binned_3
syn_dist_distribution_dendrite_spine_p50
syn_dist_distribution_dendrite_shaft_p50
dend_spine_shaft_offset
syn_size_distribution_spine_dendrite_p50
syn_size_distribution_spine_dendrite_p5
syn_size_distribution_spine_dendrite_p95
syn_size_spine_dendrite_cv
syn_size_distribution_shaft_dendrite_p50
syn_size_distribution_shaft_dendrite_p5
syn_size_distribution_shaft_dendrite_p95
syn_size_shaft_dendrite_cv
frac_syn_spine_soma
frac_syn_spine_dendrite
median_density_spine
median_density_shaft
syn_spine_shaft_ratio_dendrite
num_spine_syn_dendrite
num_shaft_syn_dendrite
num_spine_syn_soma
syn_count_dist_binned_shaft_0
syn_count_dist_binned_shaft_1
syn_count_dist_binned_shaft_2
syn_count_dist_binned_shaft_3
syn_count_dist_binned_spine_0
syn_count_dist_binned_spine_1
syn_count_dist_binned_spine_2
syn_count_dist_binned_spine_3
syn_count_dist_binned_ratio_0
syn_count_dist_binned_ratio_1
syn_count_dist_binned_ratio_2
syn_count_dist_binned_ratio_3
syn_count_pca0
syn_count_pca1
syn_count_pca2
syn_count_pca3
syn_count_pca4
syn_count_pca5
syn_count_pca6
syn_count_pca7
syn_count_pca8
syn_count_pca9
branch_svd0
branch_svd1
branch_svd2
branch_svd3
branch_svd4
ego_count_pca0
ego_count_pca1
ego_count_pca2

### soma position info

In [4]:
anatomy = pl.read_delta("/data/microns1412/cellfeatures/minnie65_std_transform_coordinates").drop(['project_id','feature_set_id'])
anatomy.head()

shape: (5, 4)
┌────────┬──────────────────┬──────────────────┬──────────────────┐
│ id     ┆ x_medial-lateral ┆ y_dorsal-ventral ┆ z_caudal-rostral │
│ ---    ┆ ---              ┆ ---              ┆ ---              │
│ str    ┆ f32              ┆ f32              ┆ f32              │
╞════════╪══════════════════╪══════════════════╪══════════════════╡
│ 373879 ┆ 828.189697       ┆ 638.553772       ┆ 783.719971       │
│ 201858 ┆ 510.690918       ┆ 505.672302       ┆ 1050.680054      │
│ 600774 ┆ 1255.059204      ┆ 821.799255       ┆ 777.679993       │
│ 408486 ┆ 891.15741        ┆ 662.693665       ┆ 1002.960022      │
│ 598774 ┆ 1235.960083      ┆ 809.527954       ┆ 828.52002        │
└────────┴──────────────────┴──────────────────┴──────────────────┘

### E-I type info (cluster)

In [15]:
clusters=pl.read_delta("/data/microns1412/cluster")
clusters.head()

shape: (5, 9)
┌────────────┬───────────┬────────────┬───────┬───┬───────────┬────────────┬───────────┬───────────┐
│ id         ┆ parent    ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_c ┆ distance_ ┆ project_i │
│ ---        ┆ ---       ┆ ---        ┆ ---   ┆   ┆ ---       ┆ ategory    ┆ to_parent ┆ d         │
│ str        ┆ str       ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---        ┆ ---       ┆ ---       │
│            ┆           ┆            ┆       ┆   ┆           ┆ str        ┆ f64       ┆ str       │
╞════════════╪═══════════╪════════════╪═══════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ neuron     ┆ null      ┆ ["glutamat ┆ 0     ┆ … ┆ #000000   ┆ major_clas ┆ null      ┆ minnie65  │
│            ┆           ┆ ergic",    ┆       ┆   ┆           ┆ s          ┆           ┆           │
│            ┆           ┆ "gabaergic ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "]         ┆       ┆   ┆           ┆            ┆           ┆           │
│ gabaergic  ┆ neuron    ┆ ["PTC",    ┆ 1     ┆ … ┆ #0000FF   ┆ class      ┆ null      ┆ minnie65  │
│            ┆           ┆ "DTC", …   ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "STC"]     ┆       ┆   ┆           ┆            ┆           ┆           │
│ glutamater ┆ neuron    ┆ ["L4IT",   ┆ 1     ┆ … ┆ #FF0000   ┆ class      ┆ null      ┆ minnie65  │
│ gic        ┆           ┆ "L6CT", …  ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "L6SP"]    ┆       ┆   ┆           ┆            ┆           ┆           │
│ PTC        ┆ gabaergic ┆ null       ┆ 2     ┆ … ┆ #364a7a   ┆ subtype    ┆ null      ┆ minnie65  │
│ DTC        ┆ gabaergic ┆ null       ┆ 2     ┆ … ┆ #80c5c0   ┆ subtype    ┆ null      ┆ minnie65  │
└────────────┴───────────┴────────────┴───────┴───┴───────────┴────────────┴───────────┴───────────┘

# Minnie

In [19]:
client = caveclient.CAVEclient("minnie65_phase3_v1", auth_token=os.environ["CUSTOM_KEY"])
version = 1412
client.materialize.version = version

In [27]:
featdef_df_minnie = pd.read_csv("../data/minnie1412/minnie_cell_features.csv")

In [28]:
featdef_df_minnie.head()

,id,description,unit,data_type,range_min,range_max
0,nucleus_volume_um,Nucleus volume,MICRONS_CUBED,<f4,0.0,NaN
1,nucleus_area_um,Nucleus surface area,MICRONS_SQUARE,<f4,0.0,NaN
2,nuclear_area_to_volume_ratio,Nucleus surface area to volume ratio,MICRONS_INVERSE,<f4,0.0,NaN
3,nuclear_folding_area_um,Area of nucleus in an infolding (see Elabbady ...,MICRONS_SQUARE,<f4,0.0,NaN
4,fraction_nuclear_folding,Fraction of nucleus in an infolding,RATIO,<f4,0.0,1.0

In [29]:
print("\n".join(featdef_df_minnie["id"].to_list()))

nucleus_volume_um
nucleus_area_um
nuclear_area_to_volume_ratio
nuclear_folding_area_um
fraction_nuclear_folding
nucleus_to_soma_ratio
soma_volume_um
soma_area_um
soma_to_nucleus_center_dist
soma_area_to_volume_ratio
soma_synapse_density_um
tip_len_dist_dendrite_p75
tip_tort_dendrite_p75
num_syn_dendrite
num_syn_soma
path_length_dendrite
radial_extent_dendrite
syn_dist_distribution_dendrite_p50
syn_size_distribution_soma_p50
syn_size_distribution_dendrite_p50
syn_size_distribution_dendrite_p5
syn_size_distribution_dendrite_p95
syn_size_dendrite_cv
syn_depth_dist_p1
syn_depth_dist_p99
syn_depth_extent
median_density
radius_dist
area_factor
dendrite_length_binned_0
dendrite_length_binned_1
dendrite_length_binned_2
dendrite_length_binned_3
syn_dist_distribution_dendrite_spine_p50
syn_dist_distribution_dendrite_shaft_p50
dend_spine_shaft_offset
syn_size_distribution_spine_dendrite_p50
syn_size_distribution_spine_dendrite_p5
syn_size_distribution_spine_dendrite_p95
syn_size_spine_dendrite_cv
syn_size_distribution_shaft_dendrite_p50
syn_size_distribution_shaft_dendrite_p5
syn_size_distribution_shaft_dendrite_p95
syn_size_shaft_dendrite_cv
frac_syn_spine_soma
frac_syn_spine_dendrite
median_density_spine
median_density_shaft
syn_spine_shaft_ratio_dendrite
num_spine_syn_dendrite
num_shaft_syn_dendrite
num_spine_syn_soma
syn_count_dist_binned_shaft_0
syn_count_dist_binned_shaft_1
syn_count_dist_binned_shaft_2
syn_count_dist_binned_shaft_3
syn_count_dist_binned_spine_0
syn_count_dist_binned_spine_1
syn_count_dist_binned_spine_2
syn_count_dist_binned_spine_3
syn_count_dist_binned_ratio_0
syn_count_dist_binned_ratio_1
syn_count_dist_binned_ratio_2
syn_count_dist_binned_ratio_3
syn_count_pca0
syn_count_pca1
syn_count_pca2
syn_count_pca3
syn_count_pca4
syn_count_pca5
syn_count_pca6
syn_count_pca7
syn_count_pca8
syn_count_pca9
branch_svd0
branch_svd1
branch_svd2
branch_svd3
branch_svd4
ego_count_pca0
ego_count_pca1
ego_count_pca2

# VISP

In [32]:
visp_exc_featset_df = pd.read_csv("../data/visp-features-and-mapping/exc_visp_patchseq_morph_feature_definitions.csv")

In [33]:
visp_inh_featset_df = pd.read_csv("../data/visp-features-and-mapping/inh_visp_patchseq_morph_feature_definitions.csv")

In [9]:
# WNM morph features
wnm_feature_matrix = pd.read_csv("/data/visp-features-and-mapping/RawFeaturesWide_ChamferCorr.csv", index_col=0)

In [40]:
print("\n".join(visp_exc_featset_df["id"].to_list()))

apical_dendrite_bias_x
apical_dendrite_bias_y
apical_dendrite_depth_pc_0
apical_dendrite_depth_pc_1
apical_dendrite_depth_pc_2
apical_dendrite_depth_pc_3
apical_dendrite_early_branch_path
apical_dendrite_emd_with_basal_dendrite
apical_dendrite_extent_x
apical_dendrite_extent_y
apical_dendrite_frac_above_basal_dendrite
apical_dendrite_frac_below_basal_dendrite
apical_dendrite_frac_intersect_basal_dendrite
apical_dendrite_max_branch_order
apical_dendrite_max_euclidean_distance
apical_dendrite_max_path_distance
apical_dendrite_mean_contraction
apical_dendrite_mean_diameter
apical_dendrite_mean_moments_along_max_distance_projection
apical_dendrite_num_branches
apical_dendrite_num_outer_bifurcations
apical_dendrite_soma_percentile_x
apical_dendrite_soma_percentile_y
apical_dendrite_std_moments_along_max_distance_projection
apical_dendrite_total_length
apical_dendrite_total_surface_area
axon_exit_distance
axon_exit_theta
basal_dendrite_bias_x
basal_dendrite_bias_y
basal_dendrite_calculate_number_of_stems
basal_dendrite_extent_x
basal_dendrite_extent_y
basal_dendrite_frac_above_apical_dendrite
basal_dendrite_frac_below_apical_dendrite
basal_dendrite_frac_intersect_apical_dendrite
basal_dendrite_max_branch_order
basal_dendrite_max_euclidean_distance
basal_dendrite_max_path_distance
basal_dendrite_mean_contraction
basal_dendrite_mean_diameter
basal_dendrite_num_branches
basal_dendrite_soma_percentile_x
basal_dendrite_soma_percentile_y
basal_dendrite_stem_exit_down
basal_dendrite_stem_exit_side
basal_dendrite_stem_exit_up
basal_dendrite_total_length
basal_dendrite_total_surface_area
soma_aligned_dist_from_pia

In [41]:
print("\n".join(visp_inh_featset_df["id"].to_list()))

axon_bias_x
axon_bias_y
axon_depth_pc_0
axon_depth_pc_1
axon_depth_pc_2
axon_depth_pc_3
axon_depth_pc_4
axon_depth_pc_5
axon_emd_with_basal_dendrite
axon_exit_distance
axon_exit_theta
axon_extent_x
axon_extent_y
axon_frac_above_basal_dendrite
axon_frac_below_basal_dendrite
axon_frac_intersect_basal_dendrite
axon_max_branch_order
axon_max_euclidean_distance
axon_max_path_distance
axon_mean_contraction
axon_num_branches
axon_soma_percentile_x
axon_soma_percentile_y
axon_total_length
basal_dendrite_bias_x
basal_dendrite_bias_y
basal_dendrite_calculate_number_of_stems
basal_dendrite_extent_x
basal_dendrite_extent_y
basal_dendrite_frac_above_axon
basal_dendrite_frac_below_axon
basal_dendrite_frac_intersect_axon
basal_dendrite_max_branch_order
basal_dendrite_max_euclidean_distance
basal_dendrite_max_path_distance
basal_dendrite_mean_contraction
basal_dendrite_mean_diameter
basal_dendrite_num_branches
basal_dendrite_soma_percentile_x
basal_dendrite_soma_percentile_y
basal_dendrite_stem_exit_down
basal_dendrite_stem_exit_side
basal_dendrite_stem_exit_up
basal_dendrite_total_length
basal_dendrite_total_surface_area
soma_aligned_dist_from_pia

In [10]:
print("\n".join(wnm_feature_matrix.columns.to_list()))

swc_path
soma_aligned_dist_from_pia
basal_dendrite_max_euclidean_distance
apical_dendrite_num_branches
basal_dendrite_stem_exit_down
apical_dendrite_bias_y
apical_dendrite_extent_y
apical_dendrite_depth_pc_0
apical_dendrite_early_branch_path
apical_dendrite_mean_contraction
apical_dendrite_soma_percentile_y
basal_dendrite_frac_above_apical_dendrite
basal_dendrite_extent_y
apical_dendrite_max_branch_order
apical_dendrite_total_length
apical_dendrite_mean_moments_along_max_distance_projection
basal_dendrite_total_length
basal_dendrite_bias_y
apical_dendrite_depth_pc_2
apical_dendrite_soma_percentile_x
apical_dendrite_depth_pc_3
basal_dendrite_extent_x
basal_dendrite_max_branch_order
basal_dendrite_max_path_distance
apical_dendrite_frac_below_basal_dendrite
apical_dendrite_frac_above_basal_dendrite
apical_dendrite_frac_intersect_basal_dendrite
basal_dendrite_soma_percentile_y
basal_dendrite_soma_percentile_x
apical_dendrite_max_euclidean_distance
basal_dendrite_stem_exit_up
apical_dendrite_emd_with_basal_dendrite
basal_dendrite_num_branches
basal_dendrite_stem_exit_side
basal_dendrite_frac_intersect_apical_dendrite
apical_dendrite_extent_x
apical_dendrite_std_moments_along_max_distance_projection
apical_dendrite_num_outer_bifurcations
apical_dendrite_max_path_distance
apical_dendrite_depth_pc_1
basal_dendrite_calculate_number_of_stems
basal_dendrite_mean_contraction
apical_dendrite_bias_x
basal_dendrite_bias_x
basal_dendrite_frac_below_apical_dendrite

In [16]:
clusters=pl.read_delta("/data/microns1412/cluster")
clusters.head()

shape: (5, 9)
┌────────────┬───────────┬────────────┬───────┬───┬───────────┬────────────┬───────────┬───────────┐
│ id         ┆ parent    ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_c ┆ distance_ ┆ project_i │
│ ---        ┆ ---       ┆ ---        ┆ ---   ┆   ┆ ---       ┆ ategory    ┆ to_parent ┆ d         │
│ str        ┆ str       ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---        ┆ ---       ┆ ---       │
│            ┆           ┆            ┆       ┆   ┆           ┆ str        ┆ f64       ┆ str       │
╞════════════╪═══════════╪════════════╪═══════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ neuron     ┆ null      ┆ ["glutamat ┆ 0     ┆ … ┆ #000000   ┆ major_clas ┆ null      ┆ minnie65  │
│            ┆           ┆ ergic",    ┆       ┆   ┆           ┆ s          ┆           ┆           │
│            ┆           ┆ "gabaergic ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "]         ┆       ┆   ┆           ┆            ┆           ┆           │
│ gabaergic  ┆ neuron    ┆ ["PTC",    ┆ 1     ┆ … ┆ #0000FF   ┆ class      ┆ null      ┆ minnie65  │
│            ┆           ┆ "DTC", …   ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "STC"]     ┆       ┆   ┆           ┆            ┆           ┆           │
│ glutamater ┆ neuron    ┆ ["L4IT",   ┆ 1     ┆ … ┆ #FF0000   ┆ class      ┆ null      ┆ minnie65  │
│ gic        ┆           ┆ "L6CT", …  ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "L6SP"]    ┆       ┆   ┆           ┆            ┆           ┆           │
│ PTC        ┆ gabaergic ┆ null       ┆ 2     ┆ … ┆ #364a7a   ┆ subtype    ┆ null      ┆ minnie65  │
│ DTC        ┆ gabaergic ┆ null       ┆ 2     ┆ … ┆ #80c5c0   ┆ subtype    ┆ null      ┆ minnie65  │
└────────────┴───────────┴────────────┴───────┴───┴───────────┴────────────┴───────────┴───────────┘