In [5]:
from utils import get_list_differences
import polars as pl
import os 

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
DATA_ROOT = '/scratch/combined_datasets'

## Look at cell to cluster mapping of patchseq and WNM

In [15]:
df = pl.read_delta(os.path.join(DATA_ROOT, 'celltoclustermapping'))

In [16]:
df

shape: (18_171, 8)
┌─────────────┬─────────────┬─────────────┬─────────────┬───────┬─────────────┬───────┬────────────┐
│ id          ┆ mapping_set ┆ source_cell ┆ target_clus ┆ score ┆ probability ┆ notes ┆ project_id │
│ ---         ┆ ---         ┆ ---         ┆ ter         ┆ ---   ┆ ---         ┆ ---   ┆ ---        │
│ str         ┆ str         ┆ str         ┆ ---         ┆ f64   ┆ f64         ┆ str   ┆ str        │
│             ┆             ┆             ┆ str         ┆       ┆             ┆       ┆            │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══════╪═════════════╪═══════╪════════════╡
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ L5 ET-2     ┆ null  ┆ 0.988       ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-L…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 23_reg-G…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-c…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ L5 ET-3     ┆ null  ┆ 0.918       ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆             ┆       ┆             ┆       ┆ nm         │
│ 35_reg-L…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 35_reg-G…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ …           ┆ …           ┆ …           ┆ …           ┆ …     ┆ …           ┆ …     ┆ …          │
│ 645369849-c ┆ visp_exc_pa ┆ 645369849   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ ell-visp_ex ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ c_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-L ┆ visp_exc_pa ┆ 831254527   ┆ L6 CT VISp  ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ 6 CT VISp   ┆ tchseq_ttyp ┆             ┆ Ctxn3 Sla   ┆       ┆             ┆       ┆ atchseq    │
│ Ctxn3 Sla…  ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-L ┆ visp_exc_pa ┆ 831254527   ┆ L6 CT       ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ 6 CT-visp_e ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ xc_patch…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-G ┆ visp_exc_pa ┆ 831254527   ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ lutamatergi ┆ tchseq_ttyp ┆             ┆ ic          ┆       ┆             ┆       ┆ atchseq    │
│ c-visp_e…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 831254527-c ┆ visp_exc_pa ┆ 831254527   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_p │
│ ell-visp_ex ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ c_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
└─────────────┴─────────────┴─────────────┴─────────────┴───────┴─────────────┴───────┴────────────┘

In [19]:
df['mapping_set'].unique()

shape: (3,)
Series: 'mapping_set' [str]
[
	"visp_exc_wnm_mettype_mapping"
	"visp_exc_patchseq_ttype_mappin…
	"visp_inh_patchseq_ttype_mappin…
]

In [29]:
df = pl.read_delta('/data/visp_deltalakes/cluster')
df

shape: (186, 9)
┌────────────┬───────────┬────────────┬───────┬───┬───────────┬────────────┬───────────┬───────────┐
│ id         ┆ parent    ┆ children   ┆ level ┆ … ┆ hex_color ┆ heirachy_c ┆ distance_ ┆ project_i │
│ ---        ┆ ---       ┆ ---        ┆ ---   ┆   ┆ ---       ┆ ategory    ┆ to_parent ┆ d         │
│ str        ┆ str       ┆ list[str]  ┆ i64   ┆   ┆ str       ┆ ---        ┆ ---       ┆ ---       │
│            ┆           ┆            ┆       ┆   ┆           ┆ str        ┆ f64       ┆ str       │
╞════════════╪═══════════╪════════════╪═══════╪═══╪═══════════╪════════════╪═══════════╪═══════════╡
│ cell       ┆ null      ┆ ["GABAergi ┆ 0     ┆ … ┆ #000000   ┆ major_clas ┆ null      ┆ visp_met_ │
│            ┆           ┆ c", "Gluta ┆       ┆   ┆           ┆ s          ┆           ┆ types     │
│            ┆           ┆ matergic"] ┆       ┆   ┆           ┆            ┆           ┆           │
│ GABAergic  ┆ cell      ┆ ["Sst-MET- ┆ 1     ┆ … ┆ #EF4136   ┆ class      ┆ null      ┆ visp_met_ │
│            ┆           ┆ 1", "Sst-M ┆       ┆   ┆           ┆            ┆           ┆ types     │
│            ┆           ┆ ET-2", …   ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "…         ┆       ┆   ┆           ┆            ┆           ┆           │
│ Glutamater ┆ cell      ┆ ["L2/3     ┆ 1     ┆ … ┆ #27AAE1   ┆ class      ┆ null      ┆ visp_met_ │
│ gic        ┆           ┆ IT", "L4   ┆       ┆   ┆           ┆            ┆           ┆ types     │
│            ┆           ┆ IT", …     ┆       ┆   ┆           ┆            ┆           ┆           │
│            ┆           ┆ "L6b"]     ┆       ┆   ┆           ┆            ┆           ┆           │
│ Sst-MET-1  ┆ GABAergic ┆ null       ┆ 2     ┆ … ┆ #b9bb67   ┆ cluster    ┆ null      ┆ visp_met_ │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ types     │
│ Sst-MET-2  ┆ GABAergic ┆ null       ┆ 2     ┆ … ┆ #804811   ┆ cluster    ┆ null      ┆ visp_met_ │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ types     │
│ …          ┆ …         ┆ …          ┆ …     ┆ … ┆ …         ┆ …          ┆ …         ┆ …         │
│ L6b        ┆ L6b       ┆ null       ┆ 3     ┆ … ┆ #335280   ┆ cluster    ┆ null      ┆ tasic_201 │
│ Hsd17b2    ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ 8_visp_sc │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ rnaseq    │
│ VLMC Spp1  ┆ VLMC      ┆ null       ┆ 3     ┆ … ┆ #6B8059   ┆ cluster    ┆ null      ┆ tasic_201 │
│ Hs3st6     ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ 8_visp_sc │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ rnaseq    │
│ SMC Acta2  ┆ SMC       ┆ null       ┆ 3     ┆ … ┆ #807059   ┆ cluster    ┆ null      ┆ tasic_201 │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ 8_visp_sc │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ rnaseq    │
│ VLMC Osr1  ┆ VLMC      ┆ null       ┆ 3     ┆ … ┆ #664747   ┆ cluster    ┆ null      ┆ tasic_201 │
│ Cd74       ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ 8_visp_sc │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ rnaseq    │
│ OPC Pdgfra ┆ Oligo     ┆ null       ┆ 3     ┆ … ┆ #476655   ┆ cluster    ┆ null      ┆ tasic_201 │
│ Grm5       ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ 8_visp_sc │
│            ┆           ┆            ┆       ┆   ┆           ┆            ┆           ┆ rnaseq    │
└────────────┴───────────┴────────────┴───────┴───┴───────────┴────────────┴───────────┴───────────┘

In [30]:
df = pl.read_delta('/data/visp_deltalakes/clustermembership')
df

shape: (2_637, 6)
┌────────────┬───────────────┬──────────────────┬─────────────┬──────────┬───────────────────┐
│ item       ┆ cluster       ┆ membership_score ┆ probability ┆ distance ┆ project_id        │
│ ---        ┆ ---           ┆ ---              ┆ ---         ┆ ---      ┆ ---               │
│ str        ┆ str           ┆ f64              ┆ f64         ┆ f64      ┆ str               │
╞════════════╪═══════════════╪══════════════════╪═════════════╪══════════╪═══════════════════╡
│ 1039273993 ┆ L6b           ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 1039273993 ┆ Glutamatergic ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 1039273993 ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 823218199  ┆ L5 ET-3       ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ 823218199  ┆ Glutamatergic ┆ null             ┆ null        ┆ null     ┆ visp_exc_patchseq │
│ …          ┆ …             ┆ …                ┆ …           ┆ …        ┆ …                 │
│ 993245688  ┆ GABAergic     ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993245688  ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ Sncg-MET-1    ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ GABAergic     ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
│ 993283588  ┆ cell          ┆ null             ┆ null        ┆ null     ┆ visp_inh_patchseq │
└────────────┴───────────────┴──────────────────┴─────────────┴──────────┴───────────────────┘

In [31]:
df['project_id'].unique()

shape: (2,)
Series: 'project_id' [str]
[
	"visp_exc_patchseq"
	"visp_inh_patchseq"
]

In [32]:
df = pl.read_delta('/data/visp_deltalakes/celltoclustermapping')
df

shape: (18_171, 8)
┌─────────────┬─────────────┬─────────────┬─────────────┬───────┬─────────────┬───────┬────────────┐
│ id          ┆ mapping_set ┆ source_cell ┆ target_clus ┆ score ┆ probability ┆ notes ┆ project_id │
│ ---         ┆ ---         ┆ ---         ┆ ter         ┆ ---   ┆ ---         ┆ ---   ┆ ---        │
│ str         ┆ str         ┆ str         ┆ ---         ┆ f64   ┆ f64         ┆ str   ┆ str        │
│             ┆             ┆             ┆ str         ┆       ┆             ┆       ┆            │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══════╪═════════════╪═══════╪════════════╡
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ L5 ET-2     ┆ null  ┆ 0.988       ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-L…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 23_reg-G…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_6984 ┆ visp_exc_wn ┆ 182709_6984 ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2452-Y124 ┆ m_mettype_m ┆ -X2452-Y124 ┆             ┆       ┆             ┆       ┆ nm         │
│ 23_reg-c…   ┆ apping      ┆ 23_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ L5 ET-3     ┆ null  ┆ 0.918       ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆             ┆       ┆             ┆       ┆ nm         │
│ 35_reg-L…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ 182709_7126 ┆ visp_exc_wn ┆ 182709_7126 ┆ Glutamaterg ┆ null  ┆ null        ┆ null  ┆ visp_exc_w │
│ -X2913-Y105 ┆ m_mettype_m ┆ -X2913-Y105 ┆ ic          ┆       ┆             ┆       ┆ nm         │
│ 35_reg-G…   ┆ apping      ┆ 35_reg      ┆             ┆       ┆             ┆       ┆            │
│ …           ┆ …           ┆ …           ┆ …           ┆ …     ┆ …           ┆ …     ┆ …          │
│ 738925092-c ┆ visp_inh_pa ┆ 738925092   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_inh_p │
│ ell-visp_in ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ h_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 772422057-P ┆ visp_inh_pa ┆ 772422057   ┆ Pvalb Th    ┆ null  ┆ null        ┆ null  ┆ visp_inh_p │
│ valb Th Sst ┆ tchseq_ttyp ┆             ┆ Sst         ┆       ┆             ┆       ┆ atchseq    │
│ -visp_in…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 772422057-P ┆ visp_inh_pa ┆ 772422057   ┆ Pvalb       ┆ null  ┆ null        ┆ null  ┆ visp_inh_p │
│ valb-visp_i ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ nh_patch…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 772422057-G ┆ visp_inh_pa ┆ 772422057   ┆ GABAergic   ┆ null  ┆ null        ┆ null  ┆ visp_inh_p │
│ ABAergic-vi ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ sp_inh_p…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
│ 772422057-c ┆ visp_inh_pa ┆ 772422057   ┆ cell        ┆ null  ┆ null        ┆ null  ┆ visp_inh_p │
│ ell-visp_in ┆ tchseq_ttyp ┆             ┆             ┆       ┆             ┆       ┆ atchseq    │
│ h_patchs…   ┆ e_mappin…   ┆             ┆             ┆       ┆             ┆       ┆            │
└─────────────┴─────────────┴─────────────┴─────────────┴───────┴─────────────┴───────┴────────────┘

In [33]:
df['project_id'].unique()

shape: (3,)
Series: 'project_id' [str]
[
	"visp_exc_patchseq"
	"visp_exc_wnm"
	"visp_inh_patchseq"
]

- LOL annoyed:
    - **visp_exc_patchseq** — has ClusterMembership entries to **the visp_met_types**
    - **visp_exc_wnm** → mapped to **visp_met_types** and is stored in celltoClusterMapping
    - so when i want “all cells that HAVE visp_met_types” they are not in one place!